# This Docker Compose file sets up a ROS Jazzy container with GUI support
# It allows you to run ROS GUI applications like RViz or Gazebo on your host machine.
# Make sure to have Docker and Docker Compose installed on your system.

# Please refer to the README for usage instructions and prerequisites.

version: '3.8'
services:
  ros:
    # Use the official ROS Jazzy image from Docker Hub
    image: ros:jazzy
    container_name: ros_jazzy_gui
    environment:
      # Pass the host's DISPLAY variable so GUI apps know where to render
      - DISPLAY=${DISPLAY}
      # Fixes some X11 issues with Qt-based apps
      - QT_X11_NO_MITSHM=1
    volumes:
      # Mount the X11 socket so the container can talk to the host's X server
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # Mount a local workspace directory for persistent files (edit as needed)
      - ./ros_ws:/root/ros_ws
    # Use the host's network stack (needed for X11 forwarding)
    network_mode: host
    # Install Gazebo Harmonic (LTS) for ROS Jazzy on container startup
    entrypoint: ["/bin/bash", "-c", "apt-get update && apt-get install -y gazebo-harmonic ros-jazzy-gz-* && exec bash"]
    # Start a bash shell by default (you can change this to run a specific command)
    command: bash
    # Run as the current user for correct file permissions (set UID/GID in your .env file)
    user: "${UID}:${GID}"
    tty: true  # Keep the container open for interactive use
    stdin_open: true  # Allow interactive commands
