# This Docker Compose file sets up a ROS Jazzy + Gazebo Harmonic container with GUI support
# The image is built from the included Dockerfile for a reproducible, ready-to-use dev environment.
# Make sure to have Docker and Docker Compose installed on your system.

# Please refer to the README for usage instructions and prerequisites.

services:
  ros:
    # Build from the local Dockerfile (includes ROS Jazzy, Gazebo Harmonic, dev tools)
    build: .
    image: vera-ros-jazzy-gazebo:latest
    container_name: ros_jazzy_gui
    environment:
      # Pass the host's DISPLAY variable so GUI apps know where to render
      - DISPLAY=${DISPLAY}
      # Fixes some X11 issues with Qt-based apps
      - QT_X11_NO_MITSHM=1
    volumes:
      # Mount the X11 socket so the container can talk to the host's X server
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # Mount a local workspace directory for persistent files (edit as needed)
      - ./ros_ws:/root/ros_ws
    # Use the host's network stack (needed for X11 forwarding)
    network_mode: host
    command: bash
    # Run as the current user for correct file permissions (set UID/GID in your .env file)
    #user: "${UID}:${GID}" 
    tty: true  # Keep the container open for interactive use
    stdin_open: true  # Allow interactive commands
